# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название события')),
                ('event_type', models.CharField(max_length=20, verbose_name='Тип события')),
                ('start', models.DateTimeField(verbose_name='Начало события')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец события')),
            ],
        ),
    ]
