# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='days_to_repeat',
            field=models.CharField(blank=True, max_length=23, verbose_name='Дни повторения'),
        ),
    ]
